/**
 * OpenTelemetry instrumentation helpers for @cap-js/ord.
 *
 * This module follows the OTel "instrumented library" pattern:
 *  - depends ONLY on @opentelemetry/api (the contract), never the SDK
 *  - never initializes a TracerProvider / MeterProvider itself
 *  - emits no-op telemetry when no SDK is registered by the host app
 *
 * The expectation is that the host CAP application installs @cap-js/telemetry
 * (or any other OTel SDK setup), which registers global providers. Our calls
 * here will then automatically light up.
 *
 * Set NO_TELEMETRY=true to bypass instrumentation entirely (mirrors the
 * @cap-js/telemetry switch).
 */

const { trace, metrics, SpanStatusCode } = require("@opentelemetry/api");
const pkg = require("../package.json");

const disabled = !!process.env.NO_TELEMETRY;

const tracer = trace.getTracer(pkg.name, pkg.version);
const meter = metrics.getMeter(pkg.name, pkg.version);

// --- Pre-declared instruments ------------------------------------------------
// Names follow OTel naming conventions (lower.snake.case, dot separators) and
// the SAP/CPA convention of namespacing custom metrics under the library name.

const counters = {
    documentsGenerated: meter.createCounter("ord.documents.generated", {
        description: "Number of ORD documents generated by @cap-js/ord",
    }),
    metadataRequests: meter.createCounter("ord.metadata.requests", {
        description: "Number of ORD metadata documents (CSN/OAS3/AsyncAPI/MCP) served",
    }),
    builds: meter.createCounter("ord.builds", {
        description: "Number of `cds build --for ord` runs executed",
    }),
};

const histograms = {
    documentGenerationDuration: meter.createHistogram("ord.document.generation.duration", {
        unit: "ms",
        description: "Wall-clock duration of a single ORD document generation",
    }),
};

// --- Span wrappers -----------------------------------------------------------

/**
 * Run an async function inside an active span. Records exceptions, sets
 * ERROR status on throw, and always ends the span.
 */
async function withSpan(name, attributes, fn) {
    if (disabled) return fn();
    return tracer.startActiveSpan(name, { attributes }, async (span) => {
        try {
            return await fn(span);
        } catch (err) {
            span.recordException(err);
            span.setStatus({ code: SpanStatusCode.ERROR, message: err?.message });
            throw err;
        } finally {
            span.end();
        }
    });
}

/**
 * Sync variant of {@link withSpan}, used to wrap synchronous code paths such
 * as the ORD document generator in `lib/ord.js`.
 */
function withSpanSync(name, attributes, fn) {
    if (disabled) return fn();
    return tracer.startActiveSpan(name, { attributes }, (span) => {
        try {
            return fn(span);
        } catch (err) {
            span.recordException(err);
            span.setStatus({ code: SpanStatusCode.ERROR, message: err?.message });
            throw err;
        } finally {
            span.end();
        }
    });
}

module.exports = {
    tracer,
    meter,
    counters,
    histograms,
    withSpan,
    withSpanSync,
    SpanStatusCode,
    disabled,
};
