name: Test ORD Compilation Workflow

on:
  push:
    branches:
      - fix/github-actions-ord

jobs:
  test-ord:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18"

    - name: Install global dependencies
      run: |
        npm install -g @sap/cds-dk

    - name: Install @cap-js/ord locally
      run: |
        npm install file:../ord

    - name: Install project dependencies
      run: |
        npm install

    - name: Create test directories and files
      run: |
        mkdir -p ariba/srv cloud/srv erp/srv
        # Ariba Service
        echo "namespace ariba; service AribaService { entity TestEntity { key ID: UUID; }; }" > ariba/srv/model.cds
        echo "using { AribaService } from './model.cds'; service TestService { entity Test as projection on AribaService.TestEntity; }" > ariba/srv/services.cds
        # Cloud Service
        echo "namespace cloud; service CloudService { entity TestEntity { key ID: UUID; }; }" > cloud/srv/model.cds
        echo "using { CloudService } from './model.cds'; service TestService { entity Test as projection on CloudService.TestEntity; }" > cloud/srv/services.cds
        # ERP Service
        echo "namespace erp; service ErpService { entity TestEntity { key ID: UUID; }; }" > erp/srv/model.cds
        echo "using { ErpService } from './model.cds'; service TestService { entity Test as projection on ErpService.TestEntity; }" > erp/srv/services.cds


    - name: Prepare ORD documents
      run: |
        mkdir -p tmp_documents
        cds compile ./ariba/srv --to ord -o ./tmp_documents/ariba.json
        cds compile ./cloud/srv --to ord -o ./tmp_documents/cloud.json
        cds compile ./erp/srv --to ord -o ./tmp_documents/erp.json

    - name: Validate generated ORD documents
      run: |
        ls -l tmp_documents
        cat tmp_documents/ariba.json
        cat tmp_documents/cloud.json
        cat tmp_documents/erp.json
